// --- DONNÉES EXTRAITES DES IMAGES ---
const registreData = {
  nourriture: {
    title: "Nourriture & Boissons",
    headers: ["Article", "Prix (Septims)"],
    items: [
      { nom: "Filet de saumon", prix: 2 },
      { nom: "Cuisse de lapin", prix: 2 },
      { nom: "Poulet grillé", prix: 2 },
      { nom: "Rôti de faisan", prix: 2 },
      { nom: "Côtelette de venaison", prix: 5 },
      { nom: "Gigot de chèvre", prix: 7 },
      { nom: "Tourte de horqueur", prix: 7 },
      { nom: "Boeuf cuit", prix: 8 },
      { nom: "Pattes de vasard", prix: 9 },
      { nom: "Soupe au choux", prix: 5 },
      { nom: "Soupe de patates", prix: 5 },
      { nom: "Potée pomme choux", prix: 6 },
      { nom: "Soupe choux & patates", prix: 6 },
      { nom: "Soupe de tomates", prix: 6 },
      { nom: "Soupe de légumes", prix: 8 },
      { nom: "Soupe de palourdes", prix: 12 },
      { nom: "Ragout de horqueur", prix: 9 },
      { nom: "Ragout de venaison", prix: 11 },
      { nom: "Ragout de boeuf", prix: 12 },
      { nom: "Pain sec", prix: 3 },
      { nom: "Pain tressé", prix: 6 },
      { nom: "Chausson aux pommes", prix: 6 },
      { nom: "Pain complet", prix: 8 },
      { nom: "Pain patate", prix: 9 },
      { nom: "Ravioli de poulet", prix: 9 },
      { nom: "Tarte aux givréboises", prix: 10 },
      { nom: "Tarte aux raisins", prix: 10 },
      { nom: "Tarte au sucre", prix: 12 },
      { nom: "Tarte aux pommes", prix: 10 },
      { nom: "Tarte aux genièvres", prix: 10 },
      { nom: "Bière", prix: 6 },
      { nom: "Vin", prix: 7 },
      { nom: "Hydrommel", prix: 15 },
      { nom: "Featherfoot Tonic", prix: 15 },
      { nom: "Hydrommel Hydronning", prix: 50 },
    ],
  },
  sacs: {
    title: "Sacs & Sacoches",
    headers: ["Article / Équipement", "Prix (Septims)"],
    items: [
      { nom: "Patchwork satchel", prix: 40 },
      { nom: "Reinforced satchel (noire)", prix: 500 },
      { nom: "Reinforced satchel (marron)", prix: 50 },
      { nom: "Toothlock satchel", prix: 60 },
      { nom: "Sturdy pouch (noire)", prix: 300 },
      { nom: "Sturdy pouch (blanche)", prix: 40 },
      { nom: "Reinforced backpack (marron)", prix: 120 },
      { nom: "Reinforced backpack (gris)", prix: 120 },
      { nom: "Reinforced backpack (noir)", prix: 120 },
      { nom: "Reinforced backpack (vert)", prix: 120 },
      { nom: "Reinforced backpack + lantern (marron)", prix: 75 },
      { nom: "Reinforced backpack + lantern (gris)", prix: 75 },
      { nom: "Reinforced backpack + lantern (noir)", prix: 75 },
      { nom: "Reinforced backpack + lantern (vert)", prix: 75 },
      { nom: "Trader's resource", prix: 80 },
      { nom: "Trader's resource + lantern", prix: 90 },
    ],
  },
  vetements: {
    title: "Tenues & Vêtements",
    headers: ["Tenues", "Prix (Septims)"],
    items: [
      { nom: "Pantalon usé", prix: 10 },
      { nom: "Tunique de jute", prix: 10 },
      { nom: "Common clothes", prix: 35 },
      { nom: "Common robes", prix: 40 },
      { nom: "Common robes hooded", prix: 40 },
      { nom: "Belted tunic", prix: "70 / 110" },
      { nom: "Mage robes", prix: "70 / 110" },
      { nom: "Tunique avec ceinture", prix: 30 },
      { nom: "Vêtement (robe bleue et rouge style taverne)", prix: 30 },
      { nom: "Vêtement", prix: 30 },
      { nom: "Vêtement de deuil", prix: 30 },
      { nom: "Vêtement raffiné", prix: 70 },
      { nom: "Fine clothes", prix: 70 },
      { nom: "Fine clothes / Tenue de noble", prix: 300 },
      { nom: "Habit de taverne", prix: 20 },
      { nom: "Quilted surcoat", prix: 50 },
      { nom: "Quilted tunic", prix: 50 },
      { nom: "Heavily quilted surcoat", prix: 50 },
      { nom: "Monk tunic", prix: 30 },
      { nom: "Hooded monk tunic", prix: 30 },
      { nom: "Necromancer robes", prix: "commande" },
      { nom: "Hooded necromancer robes", prix: "commande" },
      { nom: "Robes", prix: 30 },
      { nom: "Traveller robes", prix: 30 },
      { nom: "Tablier de forgeron", prix: 50 },
      { nom: "Tunique de cuisinier", prix: 30 },
      { nom: "Vêtement de mineur", prix: 30 },
    ],
  },
  chapeaux: {
    title: "Couvre-chefs & Capes",
    headers: ["Article / Équipement", "Prix (Septims)"],
    items: [
      { nom: "Bonnet usé", prix: 5 },
      { nom: "Capuche", prix: 20 },
      { nom: "Chapeau", prix: 20 },
      { nom: "Chapeau de deuil", prix: 20 },
      { nom: "Chapeau raffiné", prix: 20 },
      { nom: "Toque de cuisinier", prix: 20 },
      { nom: "Cow/capuche", prix: 20 },
      { nom: "Exquisite cloak (bleu et rouge)", prix: 250 },
      { nom: "Exquisite cloak (blanc et gris)", prix: 150 },
      { nom: "Rugged cape", prix: 20 },
      { nom: "Short cloth cape", prix: 20 },
      { nom: "Leather cape", prix: 30 },
      { nom: "Fur cloak", prix: 50 },
      { nom: "Cape en lin", prix: "-" },
      { nom: "Fastened scarf", prix: 30 },
      { nom: "Gathered scarf", prix: 35 },
      { nom: "Short woven scarf", prix: 30 },
      { nom: "Loose neck gaiter", prix: 30 },
      { nom: "Rugged mask", prix: 15 },
      { nom: "Quilted mantle", prix: 40 },
      { nom: "Reinforced Mantle", prix: 40 },
    ],
  },
  chaussures: {
    title: "Gants & Chaussures",
    headers: ["Article / Équipement", "Prix (Septims)"],
    items: [
      { nom: "Gants", prix: 15 },
      { nom: "Bandés de pieds", prix: 10 },
      { nom: "Bottes", prix: 15 },
      { nom: "Bottes raffinées", prix: 20 },
      { nom: "Bottes usées", prix: 15 },
      { nom: "Chaussures", prix: 15 },
      { nom: "Sandales de moine", prix: 15 },
    ],
  },
  armes: {
    title: "Armes",
    headers: [
      "Arme",
      "Fer",
      "Acier",
      "Commun",
      "Bosmer",
      "Altmer",
      "Dwemer",
      "Verre",
    ],
    items: [
      {
        nom: "Dague",
        fer: 10,
        acier: 25,
        commun: 25,
        bosmer: 615,
        altmer: 900,
        dwemer: "-",
        verre: 5250,
      },
      {
        nom: "Épée",
        fer: 20,
        acier: 40,
        commun: 40,
        bosmer: "-",
        altmer: 1000,
        dwemer: "-",
        verre: 6250,
      },
      {
        nom: "Hache",
        fer: 25,
        acier: 45,
        commun: 45,
        bosmer: "-",
        altmer: 1100,
        dwemer: "-",
        verre: 7500,
      },
      {
        nom: "Masse",
        fer: 35,
        acier: 55,
        commun: "-",
        bosmer: "-",
        altmer: 1200,
        dwemer: "-",
        verre: 9250,
      },
      {
        nom: "Espadon",
        fer: 45,
        acier: 90,
        commun: "-",
        bosmer: "-",
        altmer: 1500,
        dwemer: "-",
        verre: 9500,
      },
      {
        nom: "Hache 2/m",
        fer: 45,
        acier: 75,
        commun: 75,
        bosmer: "-",
        altmer: 1750,
        dwemer: "-",
        verre: 9750,
      },
      {
        nom: "Marteau",
        fer: 50,
        acier: 80,
        commun: "-",
        bosmer: "-",
        altmer: 2000,
        dwemer: "-",
        verre: 15000,
      },
      {
        nom: "Arc",
        fer: 20,
        acier: 50,
        commun: 60,
        bosmer: 850,
        altmer: 1000,
        dwemer: "-",
        verre: 10000,
      },
      {
        nom: "Flèche x80",
        fer: 10,
        acier: 15,
        commun: "-",
        bosmer: "-",
        altmer: 250,
        dwemer: "-",
        verre: 5000,
      },
    ],
  },
  // NOUVELLE CATÉGORIE AJOUTÉE ICI
  armures: {
    title: "Armures & Équipements",
    headers: [
      "Type",
      "Commun",
      "Peau",
      "Fourrure",
      "Cuir",
      "Impérial",
      "Impérial (Lin)",
      "Fer",
      "Acier",
      "Bosmer Léger",
      "Bosmer Lourd",
      "Chasse sauvage",
      "Altmer",
      "Dwemer",
      "Verre",
    ],
    items: [
      {
        nom: "Tête",
        commun: "X",
        peau: 20,
        fourrure: 20,
        cuir: 20,
        imperial: "25 (Capuche)",
        imperial_lin: "65 (Doubler)",
        fer: 35,
        acier: 45,
        bosmer_leger: 525,
        bosmer_lourd: 545,
        chasse: 9250,
        altmer: 525,
        dwemer: "-",
        verre: 9250,
      },
      {
        nom: "Armure",
        commun: "50 (55 Mail)",
        peau: "50 (60 Cloutée)",
        fourrure: 70,
        cuir: 50,
        imperial: "70 (Cuir Bouilli)",
        imperial_lin: "50 (Surcoat)",
        fer: "60 (75 Bandes)",
        acier: 80,
        bosmer_leger: 1035,
        bosmer_lourd: 1045,
        chasse: 17500,
        altmer: "1025 (1375 Dorée)",
        dwemer: "-",
        verre: 17500,
      },
      {
        nom: "Gants",
        commun: 15,
        peau: 15,
        fourrure: 15,
        cuir: 15,
        imperial: "80 (Mail Hide)",
        imperial_lin: "55 (Mail Tunic)",
        fer: 25,
        acier: 45,
        bosmer_leger: 275,
        bosmer_lourd: 295,
        chasse: 5250,
        altmer: 500,
        dwemer: "-",
        verre: 5250,
      },
      {
        nom: "Bottes",
        commun: 25,
        peau: 25,
        fourrure: 25,
        cuir: 25,
        imperial: "80 (Oiled Hide)",
        imperial_lin: "60 (Hauberk)",
        fer: 35,
        acier: 60,
        bosmer_leger: 525,
        bosmer_lourd: 545,
        chasse: 9250,
        altmer: 525,
        dwemer: "-",
        verre: 9250,
      },
      {
        nom: "Bouclier",
        commun: "X",
        peau: 45,
        fourrure: 45,
        cuir: 45,
        imperial: "90 (Robe Blanc)",
        imperial_lin: "85 (Mail Jacket)",
        fer: "40 (55 Bandes)",
        acier: 60,
        bosmer_leger: "X",
        bosmer_lourd: "X",
        chasse: "X",
        altmer: 1025,
        dwemer: "-",
        verre: 17500,
      },
      {
        nom: "Total avec bouclier",
        commun: "X",
        peau: "155 (165 Cloutée)",
        fourrure: 175,
        cuir: 155,
        imperial: "90 (Robe Noir)",
        imperial_lin: "85 (Oil Jacket)",
        fer: "195 (225 Bandes)",
        acier: 290,
        bosmer_leger: "X",
        bosmer_lourd: "X",
        chasse: "X",
        altmer: "3600 (3950 Dorée)",
        dwemer: "-",
        verre: 58750,
      },
      {
        nom: "Total sans bouclier / Torse",
        commun: "90 (95 Mail)",
        peau: "110 (120 Cloutée)",
        fourrure: 130,
        cuir: 110,
        imperial: "90 (Torse)",
        imperial_lin: "170 (Torse)",
        fer: "155 (170 Bandes)",
        acier: 230,
        bosmer_leger: 2360,
        bosmer_lourd: 2430,
        chasse: 41250,
        altmer: "2575 (2925 Dorée)",
        dwemer: "-",
        verre: 41250,
      },
    ],
  },
  bijoux: {
    title: "Bijoux & Joaillerie",
    headers: ["Type", "Pierre / Métal", "Prix (Septims)"],
    items: [
      { type: "Bague", nom: "Argent, Or", prix: 30 },
      { type: "Bague", nom: "Grenat", prix: 50 },
      { type: "Bague", nom: "Améthyste", prix: 75 },
      { type: "Bague", nom: "Rubis", prix: 90 },
      { type: "Bague", nom: "Saphir", prix: 120 },
      { type: "Bague", nom: "Émeraude", prix: 200 },
      { type: "Bague", nom: "Diamant", prix: 430 },
      { type: "Collier", nom: "Argent, Or", prix: 30 },
      { type: "Collier", nom: "Grenat Parfait", prix: 60 },
      { type: "Collier", nom: "Améthyste Parfait", prix: 110 },
      { type: "Collier", nom: "Rubis Parfait", prix: 140 },
      { type: "Collier", nom: "Saphir Parfait", prix: 180 },
      { type: "Collier", nom: "Émeraude Parfait", prix: 345 },
      { type: "Collier", nom: "Diamant Parfait", prix: 800 },
      { type: "Couronne", nom: "Corindon, Argent, Or", prix: 20 },
      { type: "Couronne", nom: "Rubis", prix: 75 },
      { type: "Couronne", nom: "Saphir", prix: 100 },
      { type: "Couronne", nom: "Émeraude", prix: 200 },
      { type: "Couronne", nom: "Pierre Lune", prix: 270 },
    ],
  },
  outils: {
    title: "Capes, Accessoires & Outils",
    headers: ["Article / Équipement", "Prix (Septims)"],
    items: [
      { nom: "Collier Fourrure", prix: 20 },
      { nom: "Cape Cuir", prix: 20 },
      { nom: "Cape Animaux", prix: 35 },
      { nom: "Cape Lin", prix: 50 },
      { nom: "Pioche", prix: 10 },
      { nom: "Hache Bûcheron", prix: 10 },
      { nom: "Clé", prix: 25 },
    ],
  },
};
